### PR TITLE
Localize error messages

### PR DESCRIPTION
**Pull request by palagdan**
Resolves partially #550

### CODE REVIEW

**Review by blcham — COMMENTED** [review]
@palagdan @kostobog What do you think about the following? (

I see a lot of duplicate text, so I am thinking if it is not better to have some .error.genericError as a template (using i18next nesting -- https://www.i18next.com/translation-function/nesting):

1)
```
{
  "error": {
    "default": "Došlo k chybě",
    "genericError": "Nepodařilo se {{action}} {{object}}. {{error}}",
    "faultEvent": {
      "findAll": "{{t('error.genericError', { action: 'najít', object: 'události závad' })}}",
      "update": "{{t('error.genericError', { action: 'aktualizovat', object: 'událost závady' })}}",
      "remove": "{{t('error.genericError', { action: 'odstranit', object: 'událost závady' })}}",
      "create": "{{t('error.genericError', { action: 'vytvořit', object: 'událost závady' })}}",
      "updateRectangle": "{{t('error.genericError', { action: 'aktualizovat', object: 'obdélník' })}}",
      "getFailureMode": "{{t('error.genericError', { action: 'načíst', object: 'režim selhání události' })}}",
      "deleteFailureMode": "{{t('error.genericError', { action: 'smazat', object: 'režim selhání události' })}}",
      "updateChildrenSequence": "{{t('error.genericError', { action: 'aktualizovat', object: 'pořadí dětí' })}}",
      "getRootReusable": "{{t('error.genericError', { action: 'najít', object: 'znovu použitelné události závady' })}}",
      "getAllReusable": "{{t('error.genericError', { action: 'najít', object: 'všechny znovu použitelné události závady' })}}"
    },
    "faultTree": {
      "rootEvent": {
        "deleteViolation": "Kořenová událost stromu nemůže být smazána!"
      },
      "intermediateEventAsLeaf": "Mezilehlá událost nemůže být na konci cesty!",
      "findAll": "{{t('error.genericError', { action: 'načíst', object: 'stromy závad' })}}",
      "findAllWithFilters": "{{t('error.genericError', { action: 'načíst', object: 'stromy závad s filtry' })}}",
      "find": "{{t('error.genericError', { action: 'najít', object: 'strom závad' })}}",
      "create": "{{t('error.genericError', { action: 'vytvořit', object: 'strom závad' })}}",
      "update": "{{t('error.genericError', { action: 'aktualizovat', object: 'strom závad' })}}",
      "remove": "{{t('error.genericError', { action: 'odstranit', object: 'strom závad' })}}",
      "getTreePaths": "{{t('error.genericError', { action: 'načíst', object: 'cesty stromu' })}}",
      "getTreePathsAggregate": "{{t('error.genericError', { action: 'načíst', object: 'všechny cesty stromu' })}}",
      "calculateCutSets": "{{t('error.genericError', { action: 'vypočítat', object: 'řezové množiny stromu závad' })}}"
    },
```    
    
    
or having 


2) or having just a generic entity error 
```
{
  "error": {
    "default": "Došlo k chybě",
    "entity": {
      "findAll": "Nepodařilo se načíst {{entity}}. {{error}}",
      "find": "Nepodařilo se najít {{entity}}. {{error}}",
      "create": "Nepodařilo se vytvořit {{entity}}. {{error}}",
      "update": "Nepodařilo se aktualizovat {{entity}}. {{error}}",
      "remove": "Nepodařilo se odstranit {{entity}}. {{error}}"
    },
```

**Comment by kostobog** [comment]
@blcham 
When we optimize the text there will be grammar issues and it will be harder to maintain by translators.
Variant 2 is nice as it is compact but we should consider that it will be needed to refactor error codes for generic entity errors and also introduce a  entity type argument in `responseUtis.handleServerError`.

**Comment by blcham** [comment]
ad 1)
> When we optimize the text there will be grammar issues and it will be harder to maintain by translators.

I was not able to find any grammar issue although i do not like it much either.

ad 2)

we can discuss on the meeting.

**Comment by palagdan** [comment]
@blcham 

I wanted to discuss one more thing. How should we handle dynamic exception messages like the following with messageId:
```java
public class EntityNotFoundException extends FtaFmeaException {

    public EntityNotFoundException(String message) {
        super(message);
    }

    public static EntityNotFoundException create(String resourceName, Object identifier) {
        return new EntityNotFoundException(resourceName + " identified by " + identifier + " not found.");
    }

}
```

**Comment by kostobog** [comment]
@palagdan @blcham 
Idea for question in [comment](https://github.com/kbss-cvut/fta-fmea-ui/pull/572#issuecomment-2348747131) 
The server can send the arguments for a parametrized error message. For example:
```
public class ErrorInfo {
    private String message;
    private String messageId;
    private Map<String, String> messageArguments;
    private String requestUri;
}
```
For the example above, consider that server sends messageArguments as follows:
```
{ 
  resourceName: "Component"
  identifier: "component-id"
}
```
Message template can be declared as follows
`"errorId": " {{resourceName}} identified by  {{identifier}}  not found."`

And specific message can be constructed as:
`t(data.messageId, data.messageArguments)`

**Comment by palagdan** [comment]
@blcham 

Thanks for the tip @kostobog regarding the arguments! I've implemented it on the [backend](https://github.com/kbss-cvut/fta-fmea/pull/158)—could you take a look? I've tested these errors, and now they are localized in Czech too:

Screenshot from 2024-09-17 13-16-40
Screenshot from 2024-09-17 13-18-21
Screenshot from 2024-09-17 14-08-25
Screenshot from 2024-09-17 22-12-49

**Review by blcham — APPROVED** [review]

**Pull request merged**
