### PR TITLE
Fix for system request before auth

### PR DESCRIPTION
**Pull request by Kasmadei**

### CODE REVIEW

**Review by LaChope — APPROVED** [review]
LGTM

**Comment by LaChope** [comment]
Note that we will have to update equivalent changes with keycloack @blcham

**Comment by LaChope** [comment]
> Note that we (probably) will have to update equivalent changes with keycloack #126 @blcham, not sure how the hook works.

https://github.com/kbss-cvut/fta-fmea-ui/pull/293 might solve it.

**Review by LaChope — CHANGES_REQUESTED** [review]
Sorry, I tried the changes, it does not solve the issue.

**Comment by Kasmadei** [comment]
Let me check again

**Comment by Kasmadei** [comment]
@LaChope Added a better fix and fix for console warning.

**Comment by blcham** [comment]
@LaChope I tried fix from @Kasmadei and it works for internal-auth. 

Unfortunately it does not work for keycloak-auth:
image

**Comment by Kasmadei** [comment]
@blcham Can you provide your console pls ?

**Comment by Kasmadei** [comment]
@LaChope @blcham  Noticed a strange behavior. Even after creating a new account, I still receive 401 Unauthorized responses from the server. Were there any changes on the BE side that could affect this?

**Comment by LaChope** [comment]
@Kasmadei @blcham closing in favor of https://github.com/kbss-cvut/fta-fmea-ui/pull/309

**Pull request closed without merging**
