### PR TITLE
Node layout

### PR DESCRIPTION
**Pull request by LaChope**

### CODE REVIEW

**Review by blcham — APPROVED** [review]
LGTM

**Comment by LaChope** [comment]
@blcham sorry I forgot it tags automatically now, it should not be merged yet, next time I'll open as draft

**Comment by blcham** [comment]
hmmm ... that is not good if it tags automatically, i guess than it is more usefull to just do a group of people, so one can choose as reviewers, but without automatic assignment

**Comment by LaChope** [comment]
We can open the PR as draft so it will not tag, is it sufficient?

**Comment by LaChope** [comment]
> We can open the PR as draft so it will not tag, is it sufficient?

@blcham ?

**Comment by LaChope** [comment]
Closing in favor of #197

**Pull request closed without merging**
